[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.19"
remappings = [
    '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/',
    'deploy-fund-me/=script/'
]
ffi = true
[dependencies]
forge-std = { version = ">=0.6.2, <0.9.0", default-features = false }


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
